baseURL = "https://Chakri-24.github.io/"
languageCode = "en-us"
title = "Chakri â€“ Data Engineering Blog"
theme = "PaperMod"

[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true
  ShowToc = true
